### ISSUE TITLE
Data-update

### ISSUE THREAD

**Issue by MarkMDekker** [pbl-nl/website-carbon-budget-explorer#10]
The data-update needs to happen in three steps. This can be done and tested in series, because the tool only checks files when you go to the next page.

### Step 1: global pathways
The dimensions of the emissions variable (`GHG_globe`) in `xr_dataread.nc` has changed and this is used in the sliders and the global trajectory. In both the old and new version, `Temperature`, `Risk` and `NegEmis` are dimensions. But in the old version, there was als `TrajUnc`, which was used for the uncertainty range. This dimension is now gone. In the new versions, we've added `NonCO2red` (numerical entries) and `Timing` (strings as entries). The latter can go (i.e., always fixed at 'Immediate'), if it is a problem that its entries are strings. I can also deliver `xr_dataread.nc` with the `Timing` dimension in numerical values (i.e., 0 and 1). For both `NonCO2red` and `Timing`, we'd like to have a slider to the left. That means that there is no uncertainty range anymore in the graph. Only a single line.

### Step 2: world map
All allocations in the world map require the settings of the above (determined by the sliders), and then do the allocations. The allocation rules GDR and ECPC now have new dimensions:
ECPC:
- `Discount_factor` (default = 0.0) (<- before was 2.0, but now 0)
- `Historical_startyear` (default = 1990)

GDR:
- `Historical_startyear` (also, default = 1990)
- `RCI_weight` (default = 'Half')
- `Capability_threshold` (default = 'Th')

### Step 3: country-specific allocations
Then, here we do need to include uncertainty ranges for the allocations above, of course. I wonder how things blow up, but in principle all dimensions of all allocation rules can vary, so that a single minimum and maximum should be derived over all of them, which provide us with the uncertainty range.

However, the 'median' value (= thick line, and value in the table) should not be the full median, but the most 'reasonable selection'. That means:
- `Convergence_year` = 2050
- `Scenario` = SSP2
- All of the above named new dimensions set at their default value

**Comment by martijnvandermarel** [comment]
EDIT: moved todos to PR
